### ISSUE TITLE
TagBot failing

### ISSUE THREAD

**Issue by WhiffleFish** [JuliaPOMDP/POMDPXFiles.jl#21]
Registration for `v0.2.3` was successful, but the github repository is stuck at `v0.2.2`.

```
Did not find registry PR
Processing version v0.2.3 (86db0ff8a2b508df40be21901f835cd1464b6093)
Generating changelog for version v0.2.3 (86db0ff8a2b508df40be21901f835cd1464b6093)
Warning: No registry pull request was found for this version
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 94, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line [53](https://github.com/JuliaPOMDP/POMDPXFiles.jl/actions/runs/4234469171/jobs/7356794542#step:3:54)3, in create_release
    self._git.create_tag(version, sha, log)
  File "/root/tagbot/action/git.py", line 107, in create_tag
    self.command("push", "origin", version)
  File "/root/tagbot/action/git.py", line 71, in command
    raise Abort(f"Git command '{cmd}' failed")
tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_w4hskjmr push origin v0.2.3' failed

Response (200): {
  "status": "Submitted error report"
}
```

Same problem occurs in [FIB.jl](https://github.com/JuliaPOMDP/FIB.jl/actions/runs/4076400260)

---
Possible solution [here](https://discourse.julialang.org/t/slow-tagbot-no-repo-update-after-16-hours/80870/17).

Add contents write permission in TagBot.yml
```yaml
permissions:
  contents: write
```

**Comment by mykelk** [comment]
Other packages don't seem to be impacted and they don't have the write permissions set in TagBot.yml, such as this package:
https://github.com/sisl/BayesNets.jl

Any ideas of what is going on?

**Comment by dylan-asmar** [comment]
Fixed by updating the keys.
